from setuptools import setup, find_packages

setup(
    version="1.0",
    name="auto_subtitle",
    packages=find_packages(),
    py_modules=["auto_subtitle"],
    author="Miguel Piedrafita",
    python_requires=">=3.11,<3.12",
    install_requires = [
        "ffmpeg-python",
        "mediapipe",
        "moviepy",
        "numpy",
        "opencv-python",
        "openai",
        "openai-whisper",
        "python-dotenv",
        "python-slugify",
        "pyobjc",
        "requests",
        "scipy",
        "slugify",
        "torch",
        "torchaudio",
        "torchvision",
        "tqdm",
        "whisperx",
    ],
    description="Automatically generate and embed subtitles into your videos",
    entry_points={
        'console_scripts': ['auto_subtitle=auto_subtitle.cli:main'],
    },
    include_package_data=True,
)
